server.port=${SERVER_PORT:8080}
spring.application.name=backend-java

# MongoDB Connection (Reads from ENV / system environment)
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/emotion_db}

# FastAPI AI Microservice URL
ai.service.url=${AI_SERVICE_URL:http://localhost:8000}


